### ISSUE TITLE
Use characters in private use area for icons instead

### ISSUE THREAD

**Issue by PackmanDude** [MinersStudios/WMResources#3]
https://en.wikipedia.org/wiki/Private_Use_Areas

**Comment by PackmanDude** [comment]
This shit is made out of bad practices. Stop doing nonsense for whatever reason you're doing it.

**Comment by PackmanDude** [comment]
Also, suggestion for new issue to fix: Use gettext instead of JSON properties.

**Comment by nykonhrytsyshyn** [comment]
Oh nooooo 😭 thats my biggest mistake.
I will put you out of your misery 😿

**Comment by PackmanDude** [comment]
It's not a misery, it's an ongoing frustration.

**Comment by PackmanDude** [comment]
not that deep though

**Comment by PackmanDude** [comment]
what's the deal with the newlines, get yourself a decent text editor or whatever.

**Comment by nykonhrytsyshyn** [comment]
> what's the deal with the newlines, get yourself a decent text editor or whatever.

😔

**Comment by nykonhrytsyshyn** [comment]
Im waiting for you to write this to all people on internet who have done it the same way

**Comment by PackmanDude** [comment]
> Im waiting for you to write this to all people on internet who have done it the same way

What? Been a bad coder, overall?

**Comment by nykonhrytsyshyn** [comment]
> > Im waiting for you to write this to all people on internet who have done it the same way
> 
> What? Been a bad coder, overall?

🥺

**Comment by PackmanDude** [comment]
You put so much strain onto people on the team, it's no wonders there is no work being done nor finished.

**Comment by PackmanDude** [comment]
I like how you just ignored my replies on which you don't know what to answer and proceeded to casually talk with me, like it's my fault that you can't do the basics. ![](https://github.com/images/modules/search/mona-love.png)
