### ISSUE TITLE
Use gettext instead of JSON properties

### ISSUE THREAD

**Issue by PackmanDude** [MinersStudios/WMResources#4]
> Two different programmatic APIs can be used to access ResourceBundles. Note that both APIs work with all kinds of ResourceBundles, whether GNU gettext generated classes, or other .class or .properties files.
> 
> 1. The java.util.ResourceBundle API.
> 
>     In particular, its getString function returns a string translation. Note that a missing translation yields a MissingResourceException.
> 
>     This has the advantage of being the standard API. And it does not require any additional libraries, only the msgcat generated .properties files or the msgfmt generated .class files. But it cannot do plural handling, even if the resource was generated by msgfmt from a PO file with plural handling.
> 
> 2. The gnu.gettext.GettextResource API.
> 
>     Reference documentation in Javadoc 1.1 style format is in the [javadoc2 directory](https://www.gnu.org/software/gettext/manual/html_node/javadoc2/index.html).
> 
>     Its gettext function returns a string translation. Note that when a translation is missing, the msgid argument is returned unchanged.
> 
>     This has the advantage of having the ngettext function for plural handling and the pgettext and npgettext for strings constraint to a particular context.
> 
>     To use this API, one needs the libintl.jar file which is part of the GNU gettext package and distributed under the LGPL.

**Comment by PackmanDude** [comment]
2 core points here (for my ASD friends out there):

- Less disk space, because of how files are structured;
- > Note that when a translation is missing, the msgid argument is returned unchanged.

E.g.,
Code:

```java
				…i18n("Operation completed.");
```

Will return 

> Operation completed.

If no translation is found, meaning, you don't have to write values for properties for default translation, saving you 1 extra file and reducing extensive amount of boilerplate this codebase already has. And 2nd point: it will just use these values, if there is a server misconfiguration.

**Comment by PackmanDude** [comment]
Whatever…

**Comment by PackmanDude** [comment]
This applies not only to this repository, but just a way we could make our translations better. There is no point of using default BS provided by Oracle for you kindly, you're still using bloated masses of 3rd-party libraries on top of that without a single sign of shame on your face.

**Comment by nykonhrytsyshyn** [comment]
what the hell are you talking about

**Comment by PackmanDude** [comment]
> what the hell are you talking about

Why is this marked 'invalid'?

**Comment by PackmanDude** [comment]
Why do I always need to make a PR for you to, just kindly (as Oracle did), do nothing and press a silly button instead?

**Comment by nykonhrytsyshyn** [comment]
> > what the hell are you talking about
> 
> Why is this marked 'invalid'?

have you tried to understand why I implemented translation system in this way?

**Comment by PackmanDude** [comment]
> > > what the hell are you talking about
> > 
> > Why is this marked 'invalid'?
> 
> have you tried to understand why I implemented translation system in this way?

I did. I may be wrong, give me an insight, so we can solve this by understanding why you want it that way.
