### ISSUE TITLE
[Bug]: Broken on 1.21

### ISSUE THREAD

**Issue by PackmanDude** [MinersStudios/WMResources#7]
### Are you using a version under development?

- [X] Yes, and I confirmed that my issue is relevant with the latest unreleased commit

### Issue type

Texture and/or model contains an error

### Resource pack type

WMResources (Main)

### Describe the bug

Resource pack fails to load in Minecraft 1.21.

### Acknowledgements

- [X] I have searched the existing issues and this is a new issue and not a duplicate of any another open issue.
- [X] I have written a short but informative title.
- [X] I have filled out all of the requested information in this issue properly.

**Comment by PackmanDude** [comment]
Duplicate of #6.

**Comment by nykonhrytsyshyn** [comment]
Please send your log file with errors you are getting when loading the resource pack used after the commit https://github.com/MinersStudios/WMResources/commit/2b5a9c125f9d153167cbefb055b1b05a849574ec.
If you use any modifications, send a list of them.

(This should be set out in additional context)

**Comment by PackmanDude** [comment]
Alright.
https://pastebin.com/J3c8Zmqa

**Comment by nykonhrytsyshyn** [comment]
> Alright. https://pastebin.com/J3c8Zmqa

![image](https://github.com/user-attachments/assets/c656c82c-bd42-4619-95ba-90b3023bd79d)

**Comment by PackmanDude** [comment]
It seems like Pastebin's staff has banned my paste.
https://a.cockfile.com/MFggWq.log

**Comment by PackmanDude** [comment]
Huh.
